version: '3'
services:

  client:
    container_name: client
    hostname: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - server

  server:
    container_name: server
    hostname: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
